linters:
  fast: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

    - bodyclose
    - gocritic

#    - asciicheck
#    - depguard
#    - dogsled
#    - dupl
#    - exhaustive
#    - exportloopref
#    - funlen
#    - gochecknoglobals
#    - gochecknoinits
#    - gocognit
#    - goconst
#    - gocyclo
#    - godot
#    - godox
#    - goerr113
#    - gofmt
#    - gofumpt
#    - goheader
#    - goimports
#    - golint
#    - gomnd
#    - gomodguard
#    - goprintffuncname
#    - gosec
#    - interfacer
#    - lll
#    - maligned
#    - megacheck
#    - misspell
#    - nakedret
#    - nestif
#    - noctx
#    - nolintlint
#    - prealloc
#    - rowserrcheck
#    - scopelint
#    - sqlclosecheck
#    - stylecheck
#    - testpackage
#    - unconvert
#    - unparam
#    - whitespace
#    - wsl

#    - https://github.com/kyoh86/looppointer
